defmodule AlexandriaDev.Repo.Migrations.InitialConsumerResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tags, primary_key: false) do
      add(:slug, :text, null: false, primary_key: true)
      add(:name, :map, null: false)
      add(:description, :map)
      add(:metainfo, :map, default: %{})
      add(:created_by_user, :text)
      add(:created_by_group, :text)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:modified_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:tag_synonym_group_id, :uuid)
    end

    create table(:tag_synonym_groups, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:tags) do
      modify(
        :tag_synonym_group_id,
        references(:tag_synonym_groups,
          column: :id,
          name: "tags_tag_synonym_group_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:tag_synonym_groups) do
      add(:name, :map, null: false)
    end

    create table(:marks, primary_key: false) do
      add(:slug, :text, null: false, primary_key: true)
      add(:name, :map, null: false)
      add(:description, :map)
      add(:metainfo, :map, default: %{})
      add(:created_by_user, :text)
      add(:created_by_group, :text)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:modified_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:files, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:variant, :text, null: false, default: "original")
      add(:content, :text, null: false)
      add(:mime_type, :text, null: false)
      add(:size, :bigint, null: false)
      add(:checksum, :text, null: false)
      add(:metainfo, :map, default: %{})
      add(:created_by_user, :text)
      add(:created_by_group, :text)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:modified_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:document_id, :uuid, null: false)
      add(:original_id, :uuid)
    end

    create table(:documents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:files) do
      modify(
        :document_id,
        references(:documents,
          column: :id,
          name: "files_document_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :original_id,
        references(:files,
          column: :id,
          name: "files_original_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:documents) do
      add(:title, :map, null: false)
      add(:description, :map)
      add(:date, :date)
      add(:metainfo, :map, default: %{})
      add(:created_by_user, :text)
      add(:created_by_group, :text)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:modified_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:category_id, :text, null: false)
    end

    create table(:document_tags, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :document_id,
        references(:documents,
          column: :id,
          name: "document_tags_document_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :tag_id,
        references(:tags,
          column: :slug,
          name: "document_tags_tag_id_fkey",
          type: :text,
          prefix: "public"
        ), null: false)
    end

    create table(:document_marks, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :document_id,
        references(:documents,
          column: :id,
          name: "document_marks_document_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :mark_id,
        references(:marks,
          column: :slug,
          name: "document_marks_mark_id_fkey",
          type: :text,
          prefix: "public"
        ), null: false)
    end

    create table(:categories, primary_key: false) do
      add(:slug, :text, null: false, primary_key: true)
    end

    alter table(:documents) do
      modify(
        :category_id,
        references(:categories,
          column: :slug,
          name: "documents_category_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    alter table(:categories) do
      add(:name, :map, null: false)
      add(:description, :map)
      add(:color, :text, null: false)
      add(:sort, :bigint, default: 0)
      add(:metainfo, :map, null: false, default: %{})
      add(:created_by_user, :text)
      add(:created_by_group, :text)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:modified_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :parent_id,
        references(:categories,
          column: :slug,
          name: "categories_parent_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:categories, "categories_parent_id_fkey"))

    alter table(:categories) do
      remove(:parent_id)
      remove(:modified_at)
      remove(:created_at)
      remove(:created_by_group)
      remove(:created_by_user)
      remove(:metainfo)
      remove(:sort)
      remove(:color)
      remove(:description)
      remove(:name)
    end

    drop(constraint(:documents, "documents_category_id_fkey"))

    alter table(:documents) do
      modify(:category_id, :text)
    end

    drop(table(:categories))

    drop(constraint(:document_marks, "document_marks_document_id_fkey"))

    drop(constraint(:document_marks, "document_marks_mark_id_fkey"))

    drop(table(:document_marks))

    drop(constraint(:document_tags, "document_tags_document_id_fkey"))

    drop(constraint(:document_tags, "document_tags_tag_id_fkey"))

    drop(table(:document_tags))

    alter table(:documents) do
      remove(:category_id)
      remove(:modified_at)
      remove(:created_at)
      remove(:created_by_group)
      remove(:created_by_user)
      remove(:metainfo)
      remove(:date)
      remove(:description)
      remove(:title)
    end

    drop(constraint(:files, "files_document_id_fkey"))

    drop(constraint(:files, "files_original_id_fkey"))

    alter table(:files) do
      modify(:original_id, :uuid)
      modify(:document_id, :uuid)
    end

    drop(table(:documents))

    drop(table(:files))

    drop(table(:marks))

    alter table(:tag_synonym_groups) do
      remove(:name)
    end

    drop(constraint(:tags, "tags_tag_synonym_group_id_fkey"))

    alter table(:tags) do
      modify(:tag_synonym_group_id, :uuid)
    end

    drop(table(:tag_synonym_groups))

    drop(table(:tags))
  end
end
