defmodule Alexandria.Repo.Migrations.AddDocumentAndJoins do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:alexandria_core_document_tags, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:document_id, :uuid, null: false)
      add(:tag_id, :text, null: false)
    end

    create table(:alexandria_core_document_marks, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:document_id, :uuid, null: false)
      add(:mark_id, :text, null: false)
    end

    create table(:alexandria_core_document, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:alexandria_core_document_tags) do
      modify(
        :document_id,
        references(:alexandria_core_document,
          column: :id,
          name: "alexandria_core_document_tags_document_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :tag_id,
        references(:alexandria_core_tag,
          column: :slug,
          name: "alexandria_core_document_tags_tag_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    alter table(:alexandria_core_document_marks) do
      modify(
        :document_id,
        references(:alexandria_core_document,
          column: :id,
          name: "alexandria_core_document_marks_document_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :mark_id,
        references(:alexandria_core_mark,
          column: :slug,
          name: "alexandria_core_document_marks_mark_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    alter table(:alexandria_core_document) do
      add(:title, :map, null: false)
      add(:description, :map)
      add(:date, :date)
      add(:metainfo, :map, default: %{})
      add(:created_by_user, :text)
      add(:created_by_group, :text)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:modified_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :category_id,
        references(:alexandria_core_category,
          column: :slug,
          name: "alexandria_core_document_category_id_fkey",
          type: :text,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:alexandria_core_document, "alexandria_core_document_category_id_fkey"))

    alter table(:alexandria_core_document) do
      remove(:category_id)
      remove(:modified_at)
      remove(:created_at)
      remove(:created_by_group)
      remove(:created_by_user)
      remove(:metainfo)
      remove(:date)
      remove(:description)
      remove(:title)
    end

    drop(
      constraint(
        :alexandria_core_document_marks,
        "alexandria_core_document_marks_document_id_fkey"
      )
    )

    drop(
      constraint(:alexandria_core_document_marks, "alexandria_core_document_marks_mark_id_fkey")
    )

    alter table(:alexandria_core_document_marks) do
      modify(:mark_id, :text)
      modify(:document_id, :uuid)
    end

    drop(
      constraint(:alexandria_core_document_tags, "alexandria_core_document_tags_document_id_fkey")
    )

    drop(constraint(:alexandria_core_document_tags, "alexandria_core_document_tags_tag_id_fkey"))

    alter table(:alexandria_core_document_tags) do
      modify(:tag_id, :text)
      modify(:document_id, :uuid)
    end

    drop(table(:alexandria_core_document))

    drop(table(:alexandria_core_document_marks))

    drop(table(:alexandria_core_document_tags))
  end
end
