defmodule Alexandria.Repo.Migrations.AddTagTagSynonymGroupMark do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:alexandria_core_tagsynonymgroup, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :map, null: false)
    end

    create table(:alexandria_core_tag, primary_key: false) do
      add(:slug, :text, null: false, primary_key: true)
      add(:name, :map, null: false)
      add(:description, :map)
      add(:metainfo, :map, default: %{})
      add(:created_by_user, :text)
      add(:created_by_group, :text)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:modified_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :tag_synonym_group_id,
        references(:alexandria_core_tagsynonymgroup,
          column: :id,
          name: "alexandria_core_tag_tag_synonym_group_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:alexandria_core_mark, primary_key: false) do
      add(:slug, :text, null: false, primary_key: true)
      add(:name, :map, null: false)
      add(:description, :map)
      add(:metainfo, :map, default: %{})
      add(:created_by_user, :text)
      add(:created_by_group, :text)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:modified_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(table(:alexandria_core_mark))

    drop(constraint(:alexandria_core_tag, "alexandria_core_tag_tag_synonym_group_id_fkey"))

    drop(table(:alexandria_core_tag))

    drop(table(:alexandria_core_tagsynonymgroup))
  end
end
