defmodule Alexandria.Repo.Migrations.InitialAlexandriaCategory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:alexandria_core_category, primary_key: false) do
      add(:slug, :text, null: false, primary_key: true)
      add(:name, :map, null: false)
      add(:description, :map)
      add(:color, :text, null: false)
      add(:sort, :bigint, default: 0)
      add(:metainfo, :map, null: false, default: %{})
      add(:created_by_user, :text)
      add(:created_by_group, :text)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:modified_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :parent_id,
        references(:alexandria_core_category,
          column: :slug,
          name: "alexandria_core_category_parent_id_fkey",
          type: :text,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create constraint(:alexandria_core_category, :alexandria_core_category_color_check,
             check: """
               color ~ '^#[0-9a-fA-F]{6}$'
             """
           )
  end

  def down do
    drop_if_exists(constraint(:alexandria_core_category, :alexandria_core_category_color_check))

    drop(constraint(:alexandria_core_category, "alexandria_core_category_parent_id_fkey"))

    drop(table(:alexandria_core_category))
  end
end
