defmodule Alexandria.Repo.Migrations.AddFileChecksumAndArchivedCalc do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:alexandria_core_file) do
      add(:checksum, :text, null: false)
    end
  end

  def down do
    alter table(:alexandria_core_file) do
      remove(:checksum)
    end
  end
end
