defmodule Alexandria.Repo.Migrations.AddFile do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:alexandria_core_file, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:variant, :text, null: false, default: "original")
      add(:content, :text, null: false)
      add(:mime_type, :text, null: false)
      add(:size, :bigint, null: false)
      add(:metainfo, :map, default: %{})
      add(:created_by_user, :text)
      add(:created_by_group, :text)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:modified_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :document_id,
        references(:alexandria_core_document,
          column: :id,
          name: "alexandria_core_file_document_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :original_id,
        references(:alexandria_core_file,
          column: :id,
          name: "alexandria_core_file_original_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create constraint(:alexandria_core_file, :alexandria_core_file_variant_check,
             check: """
               variant IN ('original', 'thumbnail', 'rendering')
             """
           )
  end

  def down do
    drop_if_exists(constraint(:alexandria_core_file, :alexandria_core_file_variant_check))

    drop(constraint(:alexandria_core_file, "alexandria_core_file_document_id_fkey"))

    drop(constraint(:alexandria_core_file, "alexandria_core_file_original_id_fkey"))

    drop(table(:alexandria_core_file))
  end
end
